
package com.adstream.webservice.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.adstream.webservice.user.UserInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSOrderManagerSoap", targetNamespace = "http://www.adstream.com/WebService/Orders")
@XmlSeeAlso({
    adstream.ams.ObjectFactory.class,
    tv.adstream.publicapi.adbank.ObjectFactory.class,
    com.adstream.webservice.user.ObjectFactory.class,
    com.adstream.webservice.orders.ObjectFactory.class
})
public interface WSOrderManagerSoap {


    /**
     * Returns a list of destinations
     * 
     * @return
     *     returns com.adstream.webservice.orders.ArrayOfTvDestinationGroup
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getDestinations")
    @WebResult(name = "getDestinationsResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getDestinations", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetDestinations")
    @ResponseWrapper(localName = "getDestinationsResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetDestinationsResponse")
    public ArrayOfTvDestinationGroup getDestinations();

    /**
     * User Logon
     * 
     * @return
     *     returns com.adstream.webservice.user.UserInfo
     */
    @WebMethod(operationName = "Logon", action = "http://www.adstream.com/WebService/Orders/Logon")
    @WebResult(name = "LogonResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "Logon", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.Logon")
    @ResponseWrapper(localName = "LogonResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.LogonResponse")
    public UserInfo logon();

    /**
     * Returns the Advertiser Product List
     * 
     * @return
     *     returns com.adstream.webservice.orders.ArrayOfAdvertiser
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getAdvertiserProductList")
    @WebResult(name = "getAdvertiserProductListResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getAdvertiserProductList", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetAdvertiserProductList")
    @ResponseWrapper(localName = "getAdvertiserProductListResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetAdvertiserProductListResponse")
    public ArrayOfAdvertiser getAdvertiserProductList();

    /**
     * Returns the Advertiser Product List
     * 
     * @param agencyGuid
     * @return
     *     returns com.adstream.webservice.orders.ArrayOfAdvertiser
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getAdvertiserProductListForAgency")
    @WebResult(name = "getAdvertiserProductListForAgencyResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getAdvertiserProductListForAgency", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetAdvertiserProductListForAgency")
    @ResponseWrapper(localName = "getAdvertiserProductListForAgencyResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetAdvertiserProductListForAgencyResponse")
    public ArrayOfAdvertiser getAdvertiserProductListForAgency(
        @WebParam(name = "agencyGuid", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String agencyGuid);

    /**
     * Returns the User Group List
     * 
     * @return
     *     returns com.adstream.webservice.orders.ArrayOfUserGroup
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getUserGroups")
    @WebResult(name = "getUserGroupsResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getUserGroups", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetUserGroups")
    @ResponseWrapper(localName = "getUserGroupsResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetUserGroupsResponse")
    public ArrayOfUserGroup getUserGroups();

    /**
     * Returns the User Group List for agency
     * 
     * @param agencyGuid
     * @return
     *     returns com.adstream.webservice.orders.ArrayOfUserGroup
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getUserGroupsForAgency")
    @WebResult(name = "getUserGroupsForAgencyResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getUserGroupsForAgency", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetUserGroupsForAgency")
    @ResponseWrapper(localName = "getUserGroupsForAgencyResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetUserGroupsForAgencyResponse")
    public ArrayOfUserGroup getUserGroupsForAgency(
        @WebParam(name = "AgencyGuid", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String agencyGuid);

    /**
     * Place an order
     * 
     * @param basket
     * @param adstreamOrder
     * @return
     *     returns int
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/placeOrder")
    @WebResult(name = "placeOrderResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "placeOrder", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrder")
    @ResponseWrapper(localName = "placeOrderResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrderResponse")
    public int placeOrder(
        @WebParam(name = "AdstreamOrder", targetNamespace = "http://www.adstream.com/WebService/Orders")
        AdstreamOrderRequest adstreamOrder,
        @WebParam(name = "Basket", targetNamespace = "http://www.adstream.com/WebService/Orders")
        Boolean basket);

    /**
     * Get an order details
     * 
     * @param orderReference
     * @return
     *     returns com.adstream.webservice.orders.OrderDetails
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getOrderDetails")
    @WebResult(name = "getOrderDetailsResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getOrderDetails", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetOrderDetails")
    @ResponseWrapper(localName = "getOrderDetailsResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetOrderDetailsResponse")
    public OrderDetails getOrderDetails(
        @WebParam(name = "OrderReference", targetNamespace = "http://www.adstream.com/WebService/Orders")
        int orderReference);

    /**
     * Get all the deliveries by an asset
     * 
     * @param assetId
     * @param uniqueName
     * @return
     *     returns com.adstream.webservice.orders.ArrayOfAssetDeliveryDetails
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getAssetDeliveries")
    @WebResult(name = "getAssetDeliveriesResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getAssetDeliveries", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetAssetDeliveries")
    @ResponseWrapper(localName = "getAssetDeliveriesResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetAssetDeliveriesResponse")
    public ArrayOfAssetDeliveryDetails getAssetDeliveries(
        @WebParam(name = "uniqueName", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String uniqueName,
        @WebParam(name = "assetId", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String assetId);

    /**
     * Place an order
     * 
     * @param basket
     * @param adstreamOrder
     * @return
     *     returns com.adstream.webservice.orders.OrderDetails
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/placeOrderForSambaTech")
    @WebResult(name = "placeOrderForSambaTechResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "placeOrderForSambaTech", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrderForSambaTech")
    @ResponseWrapper(localName = "placeOrderForSambaTechResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrderForSambaTechResponse")
    public OrderDetails placeOrderForSambaTech(
        @WebParam(name = "AdstreamOrder", targetNamespace = "http://www.adstream.com/WebService/Orders")
        AdstreamOrderRequest adstreamOrder,
        @WebParam(name = "Basket", targetNamespace = "http://www.adstream.com/WebService/Orders")
        Boolean basket);

    /**
     * Place an order for Adbank5
     * 
     * @param adstreamOrder
     * @return
     *     returns com.adstream.webservice.orders.ArrayOfInt
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/placeOrderAdbank5")
    @WebResult(name = "placeOrderAdbank5Result", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "placeOrderAdbank5", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrderAdbank5")
    @ResponseWrapper(localName = "placeOrderAdbank5Response", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrderAdbank5Response")
    public ArrayOfInt placeOrderAdbank5(
        @WebParam(name = "AdstreamOrder", targetNamespace = "http://www.adstream.com/WebService/Orders")
        AdstreamOrderRequest adstreamOrder);

    /**
     * Approve delivery by Id
     * 
     * @param deliveryID
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/approve")
    @RequestWrapper(localName = "approve", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.Approve")
    @ResponseWrapper(localName = "approveResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.ApproveResponse")
    public void approve(
        @WebParam(name = "DeliveryID", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String deliveryID);

    /**
     * Approve QC of delivery by Id
     * 
     * @param deliveryID
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/approveQC")
    @RequestWrapper(localName = "approveQC", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.ApproveQC")
    @ResponseWrapper(localName = "approveQCResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.ApproveQCResponse")
    public void approveQC(
        @WebParam(name = "DeliveryID", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String deliveryID);

    /**
     * Reject delivery resending and/or reingesting an ad
     * 
     * @param deliveryID
     * @param reingest
     * @param resend
     * @param comment
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/reject")
    @RequestWrapper(localName = "reject", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.Reject")
    @ResponseWrapper(localName = "rejectResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.RejectResponse")
    public void reject(
        @WebParam(name = "DeliveryID", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String deliveryID,
        @WebParam(name = "Reingest", targetNamespace = "http://www.adstream.com/WebService/Orders")
        boolean reingest,
        @WebParam(name = "Resend", targetNamespace = "http://www.adstream.com/WebService/Orders")
        boolean resend,
        @WebParam(name = "Comment", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String comment);

    /**
     * Update the house number of delivery
     * 
     * @param deliveryID
     * @param houseNumber
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/updateHouseNumber")
    @RequestWrapper(localName = "updateHouseNumber", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.UpdateHouseNumber")
    @ResponseWrapper(localName = "updateHouseNumberResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.UpdateHouseNumberResponse")
    public void updateHouseNumber(
        @WebParam(name = "DeliveryID", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String deliveryID,
        @WebParam(name = "HouseNumber", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String houseNumber);

    /**
     * Place an order
     * 
     * @param basket
     * @param adstreamOrder
     * @param agencyGuid
     * @return
     *     returns int
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/placeOrderForAgency")
    @WebResult(name = "placeOrderForAgencyResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "placeOrderForAgency", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrderForAgency")
    @ResponseWrapper(localName = "placeOrderForAgencyResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.PlaceOrderForAgencyResponse")
    public int placeOrderForAgency(
        @WebParam(name = "AdstreamOrder", targetNamespace = "http://www.adstream.com/WebService/Orders")
        AdstreamOrderRequest adstreamOrder,
        @WebParam(name = "AgencyGuid", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String agencyGuid,
        @WebParam(name = "Basket", targetNamespace = "http://www.adstream.com/WebService/Orders")
        Boolean basket);

    /**
     * Find multiple orders  date created, job number, order reference, percent complete, PO number; set number of results per page and sorting.
     * 
     * @param count
     * @param query
     * @param offset
     * @return
     *     returns com.adstream.webservice.orders.ProductOrderResponse
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/findOrders")
    @WebResult(name = "findOrdersResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "findOrders", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.FindOrders")
    @ResponseWrapper(localName = "findOrdersResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.FindOrdersResponse")
    public ProductOrderResponse findOrders(
        @WebParam(name = "offset", targetNamespace = "http://www.adstream.com/WebService/Orders")
        int offset,
        @WebParam(name = "count", targetNamespace = "http://www.adstream.com/WebService/Orders")
        int count,
        @WebParam(name = "query", targetNamespace = "http://www.adstream.com/WebService/Orders")
        OrderQuery query);

    /**
     * Find number of multiple orders  date created, job number, order reference, percent complete, PO number; set number of results per page and sorting.
     * 
     * @param query
     * @return
     *     returns int
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/findOrdersCount")
    @WebResult(name = "findOrdersCountResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "findOrdersCount", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.FindOrdersCount")
    @ResponseWrapper(localName = "findOrdersCountResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.FindOrdersCountResponse")
    public int findOrdersCount(
        @WebParam(name = "query", targetNamespace = "http://www.adstream.com/WebService/Orders")
        OrderQuery query);

    /**
     * Retrieve the status of the order
     * 
     * @param orderReference
     * @return
     *     returns com.adstream.webservice.orders.AdstreamOrderResponse
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/getOrderStatus")
    @WebResult(name = "getOrderStatusResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "getOrderStatus", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetOrderStatus")
    @ResponseWrapper(localName = "getOrderStatusResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.GetOrderStatusResponse")
    public AdstreamOrderResponse getOrderStatus(
        @WebParam(name = "OrderReference", targetNamespace = "http://www.adstream.com/WebService/Orders")
        int orderReference);

    /**
     * Creates a New Advertiser and Product for an agency
     * 
     * @param product
     * @param advertiser
     * @return
     *     returns com.adstream.webservice.orders.AdvertiserProduct
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/createNewAdvertiserAndProduct")
    @WebResult(name = "createNewAdvertiserAndProductResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "createNewAdvertiserAndProduct", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserAndProduct")
    @ResponseWrapper(localName = "createNewAdvertiserAndProductResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserAndProductResponse")
    public AdvertiserProduct createNewAdvertiserAndProduct(
        @WebParam(name = "advertiser", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String advertiser,
        @WebParam(name = "product", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String product);

    /**
     * Creates a New Advertiser and Product for an agency
     * 
     * @param product
     * @param agency
     * @param advertiser
     * @return
     *     returns com.adstream.webservice.orders.AdvertiserProduct
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/createNewAdvertiserAndProductForAgency")
    @WebResult(name = "createNewAdvertiserAndProductForAgencyResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "createNewAdvertiserAndProductForAgency", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserAndProductForAgency")
    @ResponseWrapper(localName = "createNewAdvertiserAndProductForAgencyResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserAndProductForAgencyResponse")
    public AdvertiserProduct createNewAdvertiserAndProductForAgency(
        @WebParam(name = "agency", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String agency,
        @WebParam(name = "advertiser", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String advertiser,
        @WebParam(name = "product", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String product);

    /**
     * Creates a New Advertiser Product for an existing Advertiser of an agency
     * 
     * @param product
     * @param advertiserGUID
     * @param agencyGuid
     * @return
     *     returns com.adstream.webservice.orders.AdvertiserProduct
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/createNewAdvertiserProductForAgency")
    @WebResult(name = "createNewAdvertiserProductForAgencyResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "createNewAdvertiserProductForAgency", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserProductForAgency")
    @ResponseWrapper(localName = "createNewAdvertiserProductForAgencyResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserProductForAgencyResponse")
    public AdvertiserProduct createNewAdvertiserProductForAgency(
        @WebParam(name = "agencyGuid", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String agencyGuid,
        @WebParam(name = "advertiserGUID", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String advertiserGUID,
        @WebParam(name = "product", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String product);

    /**
     * Creates a New Advertiser Product for an existing Advertiser of an agency
     * 
     * @param product
     * @param advertiserGUID
     * @return
     *     returns com.adstream.webservice.orders.AdvertiserProduct
     */
    @WebMethod(action = "http://www.adstream.com/WebService/Orders/createNewAdvertiserProduct")
    @WebResult(name = "createNewAdvertiserProductResult", targetNamespace = "http://www.adstream.com/WebService/Orders")
    @RequestWrapper(localName = "createNewAdvertiserProduct", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserProduct")
    @ResponseWrapper(localName = "createNewAdvertiserProductResponse", targetNamespace = "http://www.adstream.com/WebService/Orders", className = "com.adstream.webservice.orders.CreateNewAdvertiserProductResponse")
    public AdvertiserProduct createNewAdvertiserProduct(
        @WebParam(name = "advertiserGUID", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String advertiserGUID,
        @WebParam(name = "product", targetNamespace = "http://www.adstream.com/WebService/Orders")
        String product);

}
