
package com.adstream.webservice.orders;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSOrderManager", targetNamespace = "http://www.adstream.com/WebService/Orders", wsdlLocation = "http://uatadbank.adstream.com/WebServiceOrders/Version2/WSOrderManager.asmx?wsdl")
public class WSOrderManager
    extends Service
{

    private final static URL WSORDERMANAGER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.adstream.webservice.orders.WSOrderManager.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.adstream.webservice.orders.WSOrderManager.class.getResource(".");
            url = new URL(baseUrl, "http://uatadbank.adstream.com/WebServiceOrders/Version2/WSOrderManager.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://uatadbank.adstream.com/WebServiceOrders/Version2/WSOrderManager.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSORDERMANAGER_WSDL_LOCATION = url;
    }

    public WSOrderManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSOrderManager() {
        super(WSORDERMANAGER_WSDL_LOCATION, new QName("http://www.adstream.com/WebService/Orders", "WSOrderManager"));
    }

    /**
     * 
     * @return
     *     returns WSOrderManagerSoap
     */
    @WebEndpoint(name = "WSOrderManagerSoap")
    public WSOrderManagerSoap getWSOrderManagerSoap() {
        return super.getPort(new QName("http://www.adstream.com/WebService/Orders", "WSOrderManagerSoap"), WSOrderManagerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSOrderManagerSoap
     */
    @WebEndpoint(name = "WSOrderManagerSoap")
    public WSOrderManagerSoap getWSOrderManagerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.adstream.com/WebService/Orders", "WSOrderManagerSoap"), WSOrderManagerSoap.class, features);
    }

}
